Update monofile.yml

diff --git a/.github/workflows/monofile.yml b/.github/workflows/monofile.yml
--- a/.github/workflows/monofile.yml
+++ b/.github/workflows/monofile.yml
@@ -26,39 +26,44 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Merge all Tex file into one
         run: |
-              cat > merge.bash << EOF
-              #!/bin/bash
-              parse()
-              {
-                  awk -v script="$0" '
-                  /^\ *(\\input|\\include)\{/ {
-                      system(script " " gensub(/^.*\{([^}]+)\}.*$/,"\\1","g"))
-                      next
-                  }
-                  {
-                      print $0;
-                  }' $1
-              }
+              cat << EOF > tmp.bash
+#!/bin/bash
+parse()
+{
+    echo "parse: \$1" > /dev/stderr
+    awk -v script="\$0" '
+    /^\ *(\\\\input|\\\\include)\{/ {
+        if (system("bash " script " " gensub(/^.*\{([^}]+)\}.*$/,"\\\\1","g"))) {
+            print "error: " \$0 > "/dev/stderr"
+        }
 
-              if [[ $# -ne 1 ]]; then
-                  echo "usage: $0 input.tex" > /dev/stderr
-                  exit 1
-              else
-                  if [[ ! -f "$1" ]]; then
-                      if [[ ! -f "$1.tex" ]]; then
-                          echo "error: $1 not a file" > /dev/stderr
-                          exit 2
-                      else
-                          parse "$1.tex"
-                      fi
-                  else
-                      parse "$1"
-                  fi
-              fi
+        next
+    }
+    {
+        print \$0;
+    }' "\$1"
+}
 
-              exit 0
-              EOF
-              bash merge.bash these_payen_2019.tex > mono.tex
+if [[ \$# -ne 1 ]]; then
+    echo "usage: \$0 input.tex" > /dev/stderr
+    echo "got    \$0 \$@;" > /dev/stderr
+    exit 1
+else
+    if [[ ! -f "\$1" ]]; then
+        if [[ ! -f "\$1.tex" ]]; then
+            echo "error: \$1 not a file" > /dev/stderr
+            exit 2
+        else
+            parse "\$1.tex"
+        fi
+    else
+        parse "\$1"
+    fi
+fi
+
+exit 0
+EOF
+              bash tmp.bash these_payen_2019.tex > mono.tex
       - name: Upload Mono TeX File PDF
         uses: actions/upload-artifact@v2
         with:
